name: Lint

"on":
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  prek:
    name: "Prek"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1

      - name: Run prek
        uses: j178/prek-action@5bc78b0e94e4feab46ff835e703547d46ee65b10 # v1.1.1
        with:
          extra-args: --skip pytest
